import { useCallback, useEffect, useMemo, useState } from 'react'
import { beginKakaoLogin, canCheckIn, canOperate, changeMemberRoles, checkIn, checkInForMember, completeKakaoLogin, DEFAULT_NOTICE, getDashboard, isAdmin, logout, removeCheckIn, saveNotice } from './lib/attendanceStore'
import './App.css'

const dayKey = (d) => `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`
const dateFromKey = (key) => new Date(`${key}T12:00:00`)
const addDays = (d, n) => new Date(d.getFullYear(), d.getMonth(), d.getDate() + n)
const addMonths = (d, n) => new Date(d.getFullYear(), d.getMonth() + n, 1)
const monthStart = (d) => new Date(d.getFullYear(), d.getMonth(), 1)
const monthTitle = (d) => new Intl.DateTimeFormat('ko-KR', { year: 'numeric', month: 'long' }).format(d)
const formatDate = (key) => new Intl.DateTimeFormat('ko-KR', { month: 'long', day: 'numeric', weekday: 'long' }).format(dateFromKey(key))
const roleLabel = (role) => ({ admin: '관리자', staff: '운영진', member: '정회원', paused: '활동중단', withdrawn: '탈퇴' }[role] || '정회원')
const quarterStart = () => { const now = new Date(); return dayKey(new Date(now.getFullYear(), Math.floor(now.getMonth() / 3) * 3, 1)) }
const quarterLabel = () => `${Math.floor(new Date().getMonth() / 3) + 1}분기`

function Login({ error = '' }) {
  const [accessCode, setAccessCode] = useState(''); const [submitting, setSubmitting] = useState(false); const [formError, setFormError] = useState('')
  const params = new URLSearchParams(window.location.search)
  const loginError = error || (params.get('login_error') === 'entry_required' ? '참여코드를 먼저 확인해 주세요.' : params.get('login_error') === 'kakao_cancelled' ? '카카오 로그인이 취소되었어요. 다시 시도해 주세요.' : '')
  const submit = async (event) => { event.preventDefault(); setSubmitting(true); setFormError(''); try { await beginKakaoLogin(accessCode.trim()) } catch (reason) { setFormError(reason.message || '참여코드를 확인해 주세요.'); setSubmitting(false) } }
  return <main className="login-page"><section className="login-intro"><div className="brand-mark">P</div><span className="eyebrow lime">PICKLIMB ATTENDANCE</span><h1>피리부는 출석체크</h1><div className="intro-line" /><p className="intro-note">카카오 계정과 참여코드로 본인만 안전하게 입장할 수 있습니다.</p></section><section className="login-panel"><div className="login-card"><span className="eyebrow">KAKAO MEMBER ACCESS</span><h2>카카오톡 입장</h2><p className="muted">참여코드 확인 후 카카오 계정을 연결해 출석 기록을 안전하게 관리합니다.</p>{(loginError || formError) && <p className="form-error">{formError || loginError}</p>}<form onSubmit={submit}><label htmlFor="access-code">참여코드</label><input id="access-code" type="password" inputMode="numeric" autoComplete="one-time-code" value={accessCode} onChange={(event) => setAccessCode(event.target.value)} placeholder="참여코드를 입력하세요" required /><button className="kakao-button" disabled={submitting}><b>k</b>{submitting ? '확인 중...' : '카카오로 입장하기'}</button></form><p className="help-text">카카오 로그인과 참여코드 확인을 모두 완료해야 입장할 수 있습니다.</p></div></section></main>
}

function DayModal({ date, records, member, onClose, onChanged, onProxy }) {
  const [loading, setLoading] = useState(false); const today = dayKey(new Date()); const mine = records.find((record) => record.memberId === member.id); const permitted = canCheckIn(member)
  const add = async () => { setLoading(true); try { await checkIn(member, date); await onChanged(); onClose() } finally { setLoading(false) } }
  const remove = async () => { if (!window.confirm('이 날짜의 내 출석을 취소할까요?')) return; setLoading(true); try { await removeCheckIn(member, date); await onChanged(); onClose() } finally { setLoading(false) } }
  const note = '탈퇴 상태에서는 과거 출석 기록만 확인할 수 있어요.'
  return <div className="modal-backdrop" onMouseDown={onClose}><section className="modal day-modal" role="dialog" aria-modal="true" onMouseDown={(e) => e.stopPropagation()}><button className="close" onClick={onClose} aria-label="닫기">×</button><span className="eyebrow">DAILY CHECK-IN</span><h2>{formatDate(date)}</h2><p className="day-description">이 날짜에 출석을 남긴 멤버입니다.</p><div className="checked-members">{records.length ? records.map((record) => <span className={`checked-person ${record.memberId === member.id ? 'mine' : ''}`} key={record.id}><b>{record.memberName.slice(0, 1)}</b>{record.memberName}{record.memberId === member.id && <em>나</em>}</span>) : <p>아직 출석을 남긴 멤버가 없어요.</p>}</div>{mine && permitted ? <button className="button outline" disabled={loading} onClick={remove}>{loading ? '처리 중...' : '내 출석 취소하기'}</button> : date <= today && permitted ? <button className="button primary" disabled={loading} onClick={add}>{loading ? '반영 중...' : '이 날짜에 출석 체크'} <span>→</span></button> : date > today ? <p className="field-note">미래 날짜에는 출석 체크를 할 수 없어요.</p> : <p className="field-note">{note}</p>}{isAdmin(member) && date <= today && <button className="button admin-proxy-button" onClick={() => onProxy(date)}>정회원 대신 출석 체크</button>}<p className="field-note">다른 멤버의 출석은 확인만 가능하며 수정하거나 삭제할 수 없어요.</p></section></div>
}

function CheckInPicker({ onClose, onPick }) { const [date, setDate] = useState(dayKey(new Date())); return <div className="modal-backdrop" onMouseDown={onClose}><section className="modal date-picker-modal" role="dialog" aria-modal="true" onMouseDown={(e) => e.stopPropagation()}><button className="close" onClick={onClose} aria-label="닫기">×</button><span className="eyebrow">CHECK-IN DATE</span><h2>출석 날짜 선택</h2><p className="day-description">운동에 참여한 날짜를 선택해 출석을 남겨 주세요.</p><form onSubmit={(e) => { e.preventDefault(); onPick(date) }}><label htmlFor="checkin-date">출석 날짜</label><input id="checkin-date" type="date" value={date} max={dayKey(new Date())} onChange={(e) => setDate(e.target.value)} required /><button className="button primary">선택한 날짜로 이동 <span>→</span></button></form></section></div> }

function AdminProxyModal({ date, members, onClose, onSaved }) {
  const [targetId, setTargetId] = useState(''); const [loading, setLoading] = useState(false); const eligible = members.filter((item) => item.role === 'member')
  const save = async (e) => { e.preventDefault(); const target = eligible.find((item) => item.id === targetId); if (!target) return; setLoading(true); try { await checkInForMember(target, date); await onSaved(); onClose() } finally { setLoading(false) } }
  return <div className="modal-backdrop" onMouseDown={onClose}><section className="modal proxy-modal" role="dialog" aria-modal="true" onMouseDown={(e) => e.stopPropagation()}><button className="close" onClick={onClose} aria-label="닫기">×</button><span className="eyebrow">ADMIN CHECK-IN</span><h2>대신 출석 체크</h2><p className="day-description">{formatDate(date)} 출석을 정회원 대신 반영합니다.</p><form onSubmit={save}><div className="proxy-member-list">{eligible.length ? eligible.map((item) => <button type="button" className={targetId === item.id ? 'selected' : ''} onClick={() => setTargetId(item.id)} key={item.id}>{item.name}</button>) : <p>카카오 로그인 이력이 있는 정회원이 없습니다.</p>}</div><button className="button primary" disabled={!targetId || loading}>{loading ? '반영 중...' : '선택한 회원 출석 반영'} <span>→</span></button></form></section></div>
}

function NoticeModal({ notice, onClose, onSaved }) { const [title, setTitle] = useState(notice.title); const [content, setContent] = useState(notice.content); const [loading, setLoading] = useState(false); const save = async (e) => { e.preventDefault(); setLoading(true); try { await saveNotice({ title: title.trim() || '피리부는 클라이머 이용가이드', content: content.trim() }); await onSaved(); onClose() } finally { setLoading(false) } }; return <div className="modal-backdrop" onMouseDown={onClose}><section className="modal" role="dialog" aria-modal="true" onMouseDown={(e) => e.stopPropagation()}><button className="close" onClick={onClose} aria-label="닫기">×</button><span className="eyebrow">ADMIN EDITOR</span><h2>공지사항 수정</h2><form onSubmit={save}><label htmlFor="notice-title">제목</label><input id="notice-title" value={title} onChange={(e) => setTitle(e.target.value)} maxLength="80" /><label htmlFor="notice-content">내용</label><textarea id="notice-content" value={content} onChange={(e) => setContent(e.target.value)} maxLength="1200" /><button className="button primary" disabled={loading}>{loading ? '저장 중...' : '저장하기'} <span>→</span></button></form></section></div> }

function Calendar({ month, records, onMove, onOpen, onCheckIn }) {
  const today = dayKey(new Date()); const first = monthStart(month); const offset = first.getDay(); const total = new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate(); const grouped = new Map(); records.forEach((r) => grouped.set(r.date, [...(grouped.get(r.date) || []), r])); const atCurrent = first.getTime() === monthStart(new Date()).getTime(); const cells = Array.from({ length: 42 }, (_, i) => { const day = i - offset + 1; if (day < 1 || day > total) return null; const key = dayKey(new Date(month.getFullYear(), month.getMonth(), day)); return { day, key, entries: grouped.get(key) || [] } })
  return <section className="calendar-card"><div className="calendar-header"><div><span className="eyebrow">PICKLIMB CHECK-IN</span><h2>{monthTitle(month)}</h2></div><div className="calendar-actions"><button className="today-check" onClick={onCheckIn}>출석 체크 <span>→</span></button><div className="calendar-controls"><button onClick={() => onMove(-1)} aria-label="이전 달">←</button><button disabled={atCurrent} onClick={() => onMove(1)} aria-label="다음 달">→</button></div></div></div><div className="weekdays">{['일', '월', '화', '수', '목', '금', '토'].map((d) => <span key={d}>{d}</span>)}</div><div className="calendar-grid">{cells.map((cell, i) => cell ? <button key={cell.key} onClick={() => onOpen(cell.key)} className={`calendar-day ${cell.entries.length ? 'recorded' : ''} ${cell.key === today ? 'today' : ''}`}><b>{cell.day}</b>{cell.entries.length > 0 && <small>{cell.entries.slice(0, 2).map((r) => r.memberName).join(' · ')}{cell.entries.length > 2 && ` 외 ${cell.entries.length - 2}`}</small>}<i>{cell.entries.length || '+'}</i></button> : <span className="calendar-blank" key={`blank-${i}`} />)}</div><p className="calendar-help">출석 체크 버튼에서 날짜를 선택할 수 있어요. 날짜를 누르면 그날 출석한 멤버를 볼 수 있습니다.</p></section>
}

function MobileTimeline({ records, member, onOpen, onCheckIn }) { const [before, setBefore] = useState(3); const [after, setAfter] = useState(3); const today = new Date(); const days = Array.from({ length: before + after + 1 }, (_, i) => addDays(today, i - before)); const grouped = new Map(); records.forEach((r) => grouped.set(r.date, [...(grouped.get(r.date) || []), r])); return <section className="mobile-timeline"><div className="mobile-list-head"><span className="eyebrow">DAILY CHECK-IN</span><h2>날짜별 출석</h2></div><button className="mobile-check-in-button" onClick={onCheckIn}>출석 체크 <span>날짜 선택 →</span></button><button className="load-more" onClick={() => setBefore((v) => v + 7)}>이전 7일 더 보기</button>{days.map((date) => { const key = dayKey(date); const entries = grouped.get(key) || []; const mine = entries.some((r) => r.memberId === member.id); return <button className={`timeline-row ${key === dayKey(today) ? 'today' : ''}`} onClick={() => onOpen(key)} key={key}><span className="timeline-date">{new Intl.DateTimeFormat('ko-KR', { month: 'short', day: 'numeric', weekday: 'short' }).format(date)}</span><span className="timeline-members">{entries.length ? `${entries.map((r) => r.memberName).join(' · ')}${mine ? ' · 나' : ''}` : '출석 기록 없음'}</span><b>{entries.length}명</b></button> })}<button className="load-more" onClick={() => setAfter((v) => v + 7)}>다음 7일 더 보기</button></section> }

function AbsentModal({ names, onClose }) { const [copied, setCopied] = useState(false); const copy = async () => { await navigator.clipboard.writeText(names.join(' ')); setCopied(true); window.setTimeout(() => setCopied(false), 1800) }; return <div className="modal-backdrop" onMouseDown={onClose}><section className="modal absent-modal" role="dialog" aria-modal="true" onMouseDown={(e) => e.stopPropagation()}><button className="close" onClick={onClose} aria-label="닫기">×</button><span className="eyebrow">QUARTERLY ABSENCE</span><h2>이번 분기 미참여 정회원</h2><button className="copy-button" onClick={copy}>{copied ? '복사 완료' : '이름들 복사하기'}</button><div className="absent-names">{names.length ? names.map((name, i) => <span key={`${name}-${i}`}>[{name}]</span>) : <p>모든 정회원이 이번 분기에 참여했어요.</p>}</div></section></div> }

function OperatorPanel({ data, member, onChanged }) {
  const [search, setSearch] = useState(''); const [expanded, setExpanded] = useState(null); const [draft, setDraft] = useState({}); const [saving, setSaving] = useState(false); const [absentOpen, setAbsentOpen] = useState(false)
  useEffect(() => setDraft(Object.fromEntries(data.members.map((item) => [item.id, item.role || 'member']))), [data.members])
  const from = quarterStart(); const allRows = data.members.map((item) => { const dates = data.records.filter((r) => r.memberId === item.id && r.date >= from).map((r) => r.date).sort().reverse(); return { ...item, role: draft[item.id] || item.role || 'member', dates, count: dates.length, lastDate: dates[0] } }); const absentNames = allRows.filter((item) => item.role === 'member' && item.count === 0).map((item) => item.name); const rows = allRows.filter((item) => item.name.includes(search.trim())).sort((a, b) => (b.lastDate || '').localeCompare(a.lastDate || '')); const changed = data.members.filter((item) => (draft[item.id] || item.role || 'member') !== (item.role || 'member')).map((item) => ({ memberId: item.id, role: draft[item.id] }))
  const save = async () => { if (!changed.length) return; setSaving(true); try { await changeMemberRoles(changed); await onChanged() } finally { setSaving(false) } }
  return <section className="admin-section" id="operations"><div className="section-head"><div><span className="eyebrow">OPERATOR VIEW</span><h2>이번 분기 참여 현황</h2><p>운영진은 전체 멤버의 출석 횟수와 참여 날짜를 확인할 수 있습니다.</p></div><label className="search"><span>⌕</span><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="이름으로 찾기" /></label></div><div className="absence-summary"><div><span>{quarterLabel()} 불참 인원</span><strong>{absentNames.length}<small>명</small></strong><p>운영진·관리자·활동중단·탈퇴 인원은 제외했습니다.</p></div><button onClick={() => setAbsentOpen(true)}>미참여 명단 보기 <span>→</span></button></div>{isAdmin(member) && <div className="role-save"><span>{changed.length ? `${changed.length}명의 권한 변경을 저장하지 않았어요.` : '권한 변경은 저장하기를 눌러야 반영됩니다.'}</span><button className="button" disabled={!changed.length || saving} onClick={save}>{saving ? '저장 중...' : '권한 저장하기'}</button></div>}<div className="member-table"><div className="member-row table-label"><span>멤버</span><span>이번 분기</span><span>마지막 참여일</span><span>권한</span></div>{rows.map((item) => <div key={item.id}><div className="member-row member-button" role="button" tabIndex="0" onClick={() => setExpanded(expanded === item.id ? null : item.id)} onKeyDown={(e) => { if (e.key === 'Enter') setExpanded(expanded === item.id ? null : item.id) }}><span className="member-name"><b className="avatar large">{item.name.slice(0, 1)}</b><b>{item.name}</b></span><span><b>{item.count}회</b></span><span>{item.lastDate ? formatDate(item.lastDate) : '아직 없음'}</span><span>{isAdmin(member) && item.id !== member.id ? <select className="role-select" value={item.role} onClick={(e) => e.stopPropagation()} onKeyDown={(e) => e.stopPropagation()} onChange={(e) => setDraft((roles) => ({ ...roles, [item.id]: e.target.value }))}><option value="member">정회원</option><option value="staff">운영진</option><option value="paused">활동중단</option><option value="withdrawn">탈퇴</option><option value="admin">관리자</option></select> : <em className={`role ${item.role}`}>{roleLabel(item.role)}</em>}</span></div>{expanded === item.id && <div className="member-dates">{item.dates.length ? item.dates.map((date) => <span key={date}>{formatDate(date)}</span>) : '이번 분기 출석 기록이 없습니다.'}</div>}</div>)}</div>{absentOpen && <AbsentModal names={absentNames} onClose={() => setAbsentOpen(false)} />}</section>
}

function Dashboard({ member, onExit }) {
  const [data, setData] = useState({ members: [], records: [], notice: DEFAULT_NOTICE }); const [month, setMonth] = useState(monthStart(new Date())); const [selectedDate, setSelectedDate] = useState(null); const [pickerOpen, setPickerOpen] = useState(false); const [proxyDate, setProxyDate] = useState(null); const [noticeOpen, setNoticeOpen] = useState(false); const [guideOpen, setGuideOpen] = useState(false); const [loading, setLoading] = useState(true)
  const refresh = useCallback(async () => { setLoading(true); try { setData(await getDashboard(member)) } finally { setLoading(false) } }, [member]); useEffect(() => { refresh() }, [refresh]); const from = quarterStart(); const ownCount = useMemo(() => data.records.filter((r) => r.memberId === member.id && r.date >= from).length, [data.records, member.id, from]); const totalCount = useMemo(() => data.records.filter((r) => r.date >= from).length, [data.records, from]); const selectedRecords = data.records.filter((r) => r.date === selectedDate); const note = data.notice || DEFAULT_NOTICE
  return <div className="dashboard"><header className="topbar"><a className="wordmark" href="#top"><span>P</span> PICKLIMB</a><nav><a href="#calendar">출석 현황</a>{canOperate(member) && <a href="#operations">이번분기참여현황</a>}<a href="#guide">공지사항 · 이용가이드</a></nav><div className="profile"><span className="avatar">{member.name.slice(0, 1)}</span><span>{member.name} · {roleLabel(member.role)}</span><button onClick={onExit}>나가기</button></div></header><main id="top" className="content"><section className="hero activity-hero"><div><span className="eyebrow lime">PICKLIMB ACTIVITY</span><h1>안전하고 행복한<br /><i>운동 라이프</i></h1><p>실제 운동 후 서로의 신뢰를 바탕으로 출석을 남겨 주세요.</p></div><div className="hero-stats"><span>이번 분기</span><strong>{ownCount}<small>회</small></strong><p>내 출석 현황</p><em>전체 {totalCount}회</em></div></section>{loading ? <div className="empty">출석 현황을 불러오는 중이에요.</div> : <><div id="calendar" className="desktop-calendar"><Calendar month={month} records={data.records} onMove={(n) => setMonth((d) => addMonths(d, n))} onOpen={setSelectedDate} onCheckIn={() => setPickerOpen(true)} /></div><MobileTimeline records={data.records} member={member} onOpen={setSelectedDate} onCheckIn={() => setPickerOpen(true)} /><section className="my-quarter"><span className="eyebrow">MY QUARTER</span><h2>이번 분기, <b>{ownCount}회</b> 함께했어요.</h2><p>{member.role === 'withdrawn' ? '탈퇴 상태에서는 과거 출석 기록만 확인할 수 있어요.' : member.role === 'paused' ? '활동중단 상태의 출석은 이번 분기 인원 집계에서 제외됩니다.' : '출석 체크는 운동에 참여한 날만 남겨 주세요.'}</p></section><section id="guide" className="guide-card"><div className="guide-summary"><div><span className="eyebrow">NOTICE · GUIDE</span><h2>{note.title}</h2></div><button className="guide-toggle" onClick={() => setGuideOpen((v) => !v)} aria-expanded={guideOpen}>{guideOpen ? '접기 ▲' : '자세히 보기 ▼'}</button></div>{guideOpen && <div className="guide-body"><p>{note.content}</p>{isAdmin(member) && <button className="text-button" onClick={() => setNoticeOpen(true)}>관리자 수정</button>}</div>}</section>{canOperate(member) && <OperatorPanel data={data} member={member} onChanged={refresh} />}</>}</main><footer>© PICKLIMB · 함께, 꾸준히.</footer>{selectedDate && <DayModal date={selectedDate} records={selectedRecords} member={member} onClose={() => setSelectedDate(null)} onChanged={refresh} onProxy={(date) => { setSelectedDate(null); setProxyDate(date) }} />}{pickerOpen && <CheckInPicker onClose={() => setPickerOpen(false)} onPick={(date) => { setPickerOpen(false); setSelectedDate(date) }} />}{proxyDate && <AdminProxyModal date={proxyDate} members={data.members} onClose={() => setProxyDate(null)} onSaved={refresh} />}{noticeOpen && <NoticeModal notice={note} onClose={() => setNoticeOpen(false)} onSaved={refresh} />}</div>
}

export default function App() {
  const [member, setMember] = useState(() => { try { return JSON.parse(sessionStorage.getItem('picklimb-kakao-member')) } catch { return null } }); const [booting, setBooting] = useState(true); const [loginError, setLoginError] = useState('')
  useEffect(() => { const finish = async () => { const token = sessionStorage.getItem('picklimb-kakao-token'); if (!token) { setBooting(false); return } try { await completeKakaoLogin(token); setMember(JSON.parse(sessionStorage.getItem('picklimb-kakao-member'))) } catch (reason) { sessionStorage.removeItem('picklimb-kakao-member'); setMember(null); setLoginError(`카카오 계정 연결에 실패했어요. ${reason?.message || ''}`) } finally { sessionStorage.removeItem('picklimb-kakao-token'); setBooting(false) } }; finish() }, [])
  const exit = async () => { await logout(); sessionStorage.removeItem('picklimb-kakao-member'); setMember(null) }
  return booting ? <main className="boot-screen">카카오 로그인 상태를 확인하고 있어요.</main> : member ? <Dashboard member={member} onExit={exit} /> : <Login error={loginError} />
}
